
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Interest;
DROP TABLE IF EXISTS Actions;

CREATE TABLE IF NOT EXISTS User (
    uid INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    gender VARCHAR(5) CHECK (gender IN ('Male', 'Female')),
    location VARCHAR(100),
    age INTEGER
);

CREATE TABLE IF NOT EXISTS Actions (
    uid1 INTEGER,
    uid2 INTEGER,
    like BOOLEAN NOT NULL,
    PRIMARY KEY (uid1, uid2),
    FOREIGN KEY (uid1) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY (uid2) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Interest (
    uid INTEGER,
    interest VARCHAR(100) NOT NULL,
    PRIMARY KEY (uid, interest),
    FOREIGN KEY (uid) REFERENCES User(id) ON DELETE CASCADE
);

